// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idzablnsepdqknjdrfho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkemFibG5zZXBkcWtuamRyZmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTA0NTYsImV4cCI6MjA2MTkyNjQ1Nn0.rzBOlD3lPZ1He3WmVpsPLZNlexE_VoTyJFXi-vb_eXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);